include device/qcom/msm8610/BoardConfig.mk

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 15728640
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 377487360
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824

ENABLE_LIBRECOVERY := true
RECOVERY_EXTERNAL_STORAGE := /storage/sdcard1

# hack to prevent llvm from building
BOARD_USE_QCOM_LLVM_CLANG_RS := true

# hack to keep things building
BOARD_KERNEL_SEPARATED_DT := false

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BLUEZ := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true

